- name: service manager
  hosts: "{{ target }}"

  vars_files:
    - vars/software.yml

  remote_user: "{{ REMOTE_USER }}"

  handlers:
  - include: handlers/main.yml

  roles:
    - service/apache
    - service/php-fpm
