- name: "php-fpm: php.ini - date.timezone"
  ini_file: dest=/etc/php.ini
            section=PHP
            option=date.timezone
            value="America/New_York"
            backup=yes
  tags:
    - php-fpm

- name: "php-fpm: php.ini - default_charset"
  ini_file: dest=/etc/php.ini
            section=PHP
            option=default_charset
            value="UTF-8"
            backup=yes
  notify:
    - restart php-fpm
  tags:
    - php-fpm
