# apache
- name: enable apache
  service: name=httpd enabled=yes
  tags:
    - apache-enable

- name: disable apache
  service: name=httpd enabled=no
  tags:
    - apache-disable

- name: restart apache
  service: name=httpd state=restarted
  tags:
    - apache-restart


# php-fpm
- name: enable php-fpm
  service: name=php-fpm enabled=yes
  tags:
    - php-enable

- name: disable php-fpm
  service: name=php-fpm enabled=no
  tags:
    - php-disable

- name: restart php-fpm
  service: name=php-fpm state=restarted
  tags:
    - php-restart


# mysql
- name: enable mysql
  service: name=mysqld enabled=yes
  tags:
    - mysql-enable

- name: disable mysql
  service: name=mysqld enabled=no
  tags:
    - mysql-disable

- name: restart mysql
  service: name=mysqld state=restarted
  tags:
    - mysql-restart


# postgre
- name: enable postgre
  service: name=postgresql-9.4 enabled=yes
  tags:
    - postgre-enable

- name: disable postgre
  service: name=postgresql-9.4 enabled=no
  tags:
    - postgre-disable

- name: restart postgre
  service: name=postgresql-9.4 state=restarted
  tags:
    - postgre-restart
